spring:
  application.name: config
  cloud:
    config.server.git.uri: git@gitlab.com:flogoe/ms_quest_config.git
    config.server.git.private-key: ${SSH_KEY}

server:
  error.whitelabel.enabled: false
  http2.enabled: true
  port: 8888
  ssl:
    enabled: true
    enabled-protocols: TLSv1.3,TLSv1.2
    key-alias: microservice
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: Admin123
    key-password: Admin123

logging:
  file.name: build/logs/application.log
  level:
    org.springframework:
      boot.actuate.endpoint.EndpointId: ERROR
      security.core.userdetails.User: ERROR
      cloud.config.server.environment.MultipleJGitEnvironmentRepository: ERROR

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: true
    health:
      show-components: always
      show-details: always